### ISSUE TITLE
Not valid image extension

### ISSUE THREAD

**Issue by IDCreativ** [diegomura/react-pdf#2652]
**Describe the bug**
I made a component and i just try to display an image but it does not work. First, I had the CORS problem but it's OK now. 

Here is my code :
```
import React from "react";
import { Text, View, Image } from "@react-pdf/renderer";
import header from "../styles/headerStyles";
import { HEADERS_URL } from "@lib/constants";

const HeaderElement = ({ debug, support }) => {

	const headerImg = support.supportHeader
		? HEADERS_URL + "/"+ support.supportHeader.imageName
		: null;

	console.log("headerImg", headerImg);

	return (
		<>
			<View style={header.headerContainer}>
				<Image source={{ uri: {headerImg}, method: "get", headers:{ "Access-Control-Allow-Origin": "*", crossOrigin: "anonymous" } }} />
			</View>
			<Text debug={debug} style={header.headerTitle}>
				{support.name}
			</Text>
		</>
	);
};

export default HeaderElement;
```

- OS: MacOS
- Browser : chrome, firefox
- React-pdf version : 3.3.8
- Next JS Version : 14.1.0

**Comment by ooga** [comment]
Hello @IDCreativ 

Can you give the url of the picture you try to load ?

The error you describe is thrown here. https://github.com/diegomura/react-pdf/blob/master/packages/image/src/resolve.js#L168

So it may have a bug in detection or your image data is corrupt.

@diegomura
Another weird behavior is that there are 2 methods to detect JPG format from a Buffer and they are not identical
https://github.com/diegomura/react-pdf/blob/master/packages/image/src/resolve.js#L160
https://github.com/diegomura/react-pdf/blob/master/packages/image/src/jpeg.js#L38

**Comment by IDCreativ** [comment]
Here is the url :
https://dashboard.agco-lisaprint.com/uploads/headers/valtra-banniere-1-6567636da034f850921862.jpg

**Comment by ooga** [comment]
it's weird !
When I recreate a small playground jpeg is detected by the 2 methods

https://codesandbox.io/p/sandbox/react-pdf-jpeg-f4r9fn

**Comment by IDCreativ** [comment]
Now i have the Cors policy error again ... :'(

I didn't have that problem on my other app but it may be because image and app were on the same domain. 

When i put this image link on the playground, i have the same problem.

**Comment by ooga** [comment]
The server hosting the image `https://dashboard.agco-lisaprint.com/uploads/headers/valtra-banniere-1-6567636da034f850921862.jpg` is not providing the header `Access-Control-Allow-Origin`

https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSMissingAllowOrigin

So you will never be able to fetch this picture from a different domain.

2 solutions :
- Add `Access-Control-Allow-Origin` header to the server response
- Fetch the picture from a backend to skip CORS

**Comment by IDCreativ** [comment]
I'm use Symfony 6.4 with API PlatForm and to handle CORS, i'm using Nelmio package 2.3. Here is my Nelmio config :
```

nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'X-Auth-Token', 'X-Auth-User']
        expose_headers: ['Link']
        max_age: 3600
    paths:
        '^/': null
```
My .env.local has this variable : 
```
CORS_ALLOW_ORIGIN='^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
```
So, the problem is : 
- All my API from Symfony/API Platform works fine with my NextJS app,
- I can't display images from localhost:8000 to localhost:3000

What am i missing ?
