### ISSUE TITLE
 Generating two blank pages

### ISSUE THREAD

**Issue by Chandee** [diegomura/react-pdf#517]
**Describe the bug**
When i try to generate a pdf file on browser, the content of my file are two blank pages, no matter what i try to put inside.

**To Reproduce**
This is the code what i call to generate
``` javascript
<PDFDownloadLink document={<RelFatura dados={this.state.excel} titulo={'Voucher a faturar'} />} fileName="Vouchers.pdf">
    {({ blob, url, loading, error }) => (loading ? <i className="fa fa-file-pdf-o"> Loading document...</i> : <i className="fa fa-file-pdf-o"> Gerar pdf </i>)}
</PDFDownloadLink>
```
this is my RelFatura

```javascript
export const RelFatura = (props) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.text}> hi</Text>
    </Page>
  </Document>
);
```

and these are my styles

```css
const styles = StyleSheet.create({
  page: {
    paddingTop: 35,
    paddingBottom: 65,
    paddingHorizontal: 35,
    paddingRight: 35,
  },
  text: {
    margin: 10,
    fontSize: 12,
    textAlign: 'justify',
    fontFamily: 'Times-Roman'
  }
});
```
i have two pages that use the pdf generator, in one of them he works perfectly i take the RelFatura and put there where it is working and the output was what i expected ( the page with hi written ) but in the other page he give the blank page bug, i try put the same code on both pages nevertheless it did the same bug (one of them still working and the other give me the bug)

**Expected behavior**
A single page with hi written

**Screenshots**
![capturar](https://user-images.githubusercontent.com/28514068/53738490-1586ef00-3e6e-11e9-9a85-c73a41a3742b.PNG)

**Desktop (please complete the following information):**
 - OS: Ubuntu, Windows
 - Browser: chorme
 - React-pdf version: 1.4.0
